# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Grafana Tempo
version: "1.5.0-rc5"
slug: tempo
description: Grafana Tempo is an open source, easy-to-use, and high-scale distributed tracing backend.
url: "https://github.com/cedricziel/ha-addon-grafana-tempo/blob/main/tempo"
watchdog: http://[HOST]:3200/ready
apparmor: false
ports:
  3200/tcp: 3200
  4317/tcp: 4317
  4318/tcp: 4318
  9411/tcp: 9411
  9095/tcp: 9095
  14268/tcp: 14268
ports_description:
  3200/tcp: Tempo
  4317/tcp: OTLP/gRPC
  4318/tcp: OTLP/HTTP
  9411/tcp: Zipkin
  9095/tcp: gRPC
  14268/tcp: Jaeger/Thrift HTTP
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
homeassistant_api: true
options:
  prometheus_url: http://24212397-mimir:8001/api/v1/push
schema:
  prometheus_url: "str"
image: "ghcr.io/cedricziel/{arch}-ha-addon-grafana-tempo"
